// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjrTT_cdWPOhFUkNR9eyb83DDsEOyHnrA',
    appId: '1:57136799034:web:79f0e415ea32c110800403',
    messagingSenderId: '57136799034',
    projectId: 'sample-7c4e5',
    authDomain: 'sample-7c4e5.firebaseapp.com',
    storageBucket: 'sample-7c4e5.appspot.com',
    measurementId: 'G-M0622B6NCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKWpI_5ODdoQ-kgREY1K-MnRMcOJQy3U',
    appId: '1:57136799034:android:4f1f39dc084809c6800403',
    messagingSenderId: '57136799034',
    projectId: 'sample-7c4e5',
    storageBucket: 'sample-7c4e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTKr1GXsdgy6TULiS8sLC4UKqw2_aJtNQ',
    appId: '1:57136799034:ios:d5b582c32a6cd575800403',
    messagingSenderId: '57136799034',
    projectId: 'sample-7c4e5',
    storageBucket: 'sample-7c4e5.appspot.com',
    iosClientId: '57136799034-m999dnd4vcpdj9vho52q79tpa2v9n9gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTKr1GXsdgy6TULiS8sLC4UKqw2_aJtNQ',
    appId: '1:57136799034:ios:d5b582c32a6cd575800403',
    messagingSenderId: '57136799034',
    projectId: 'sample-7c4e5',
    storageBucket: 'sample-7c4e5.appspot.com',
    iosClientId: '57136799034-m999dnd4vcpdj9vho52q79tpa2v9n9gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2',
  );
}
